name = "weekly-report"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[vars]
IS_CLOUDFLARE_PAGES = "1"
NEXTAUTH_URL = "https://weekly-report-6qk.pages.dev"
